openapi: 3.0.0
info:
  title: calacS
  description: calacS
  version: 1.0.0
servers:
  - url: https://localhost:3000/api/v1/
paths:
  /products:
    get:
      tags:
        - Products
      summary: Products list.
      operationId: fetchProducts
      responses:
        '200':
          description: Products list.
          content:
            application/json:
              schema:
                type: object
                properties:
                    schema:
                      type: array
                      items:
                        $ref: '#/components/schemas/Product'
    post:
      tags:
        - Products
      summary: Create New Product.
      operationId: createProduct
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '201':
          description: Product Details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'


components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: number
          description: ID of created Product.
          example: 6077195780283
        image:
          type: object
          description: Info about images from Shopify.
        name:
          type: string
          description: Human-readable name of the Product.
          example: 'Short sleeve t-shirt'
        variants:
          type: array
          description: Variants of Product.
          items:
            $ref: '#/components/schemas/ProductVariant'

    ProductVariant:
      type: object
      properties:
        id:
          type: number
          description: ID of created Product Variant.
          example: 123323232
        availableQuantity:
          type: number
          description: Quantity of Product Variant.
          example: 123
        price:
          type: number
          description: Price of Product Variant
          example: 12.32
        name:
          type: string
          description: Human-readable name of the Product.
          example: 'Short sleeve t-shirt Variant A'
